In [2]:
# 首先是需要安装那个文件gridworld.py
# 下载下来了，然后需要确定文件在的工作目录
# 接着就是判断能否正确导入

import os
print(os.getcwd())

/home/akira/PycharmProjects/OpenAIDemo


In [3]:
import gridworld

In [2]:
import tkinter

# 这里一开始总是出现问题
# sudo apt-get install python3-tk 
# 在命令行里面运行这个 安装对应py3版本的tkinter库文件
# 否则 上面那个gridworld文件会报错

In [4]:
import gym
import numpy as np


obs_n = 4
act_n = 4

In [5]:
Q = np.zeros((obs_n, act_n))

In [6]:
Q

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
t = 1

for i in range(obs_n):
    for j in range(act_n):
        Q[i][j] = t
        t += 1

print(Q)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]


In [10]:
obs_t = 2
Q_list = Q[obs_t, :]
print(Q_list)

[ 9. 10. 11. 12.]


In [12]:
maxQ = np.max(Q_list)
print(maxQ, type(maxQ))

12.0 <class 'numpy.float64'>


In [13]:
action_list = np.where(Q_list == maxQ)[0]

In [14]:
action_list

array([3])

好的 现在明白了
其实找到的值就是动作本身！
剩下的好理解了，其实就是选择这个state下面奖励最多的那个action
同样奖励的action可能也不止一个，所以从这些中随机选择一个。
可能是我先看的sarsa，所以觉得它比ql的要简单
但是好像不是，我现在对sarsa的理解到位了，但是ql的还是不够

顺便看了一下，这个项目后面的几个作业都还蛮不错的
有意思，想要做到！
顺便把这几个算法好好理解下！

用sample而不用predict的原因：
1 一开始的Q值是不准确的
2 有一定的随机性才能寻找出最佳路径来：保证其他的动作有一定的可能性被选出来
